"""
Populate TerraMind AI agriculture KB documents with REAL authoritative
source-backed crop production / agricultural-overview content.

Source URLs are real, public, and on hosts inside the configured trusted tiers
(.edu cooperative extension, FAO, USDA ERS national agencies). Every URL in
this module is checked by scripts/verify_agriculture_sources.py before the
documents are written.

Scope per document (per the placeholder instructions): agro-ecological zones
suited to the crop, typical yield ranges, rotation partners, cover-cropping
integration, economic importance, major production regions and climate
adaptation.

RULES FOLLOWED (identical to the disease / treatment / fertilizer / plant_care
KB phases):
- PRESERVE existing document_id, crop, class_label, filename and schema.
- Set metadata.status = 'sourced', placeholder_replaced = 'true',
  last_reviewed = 2026-09-22.
- Do NOT touch ML / training / RAG / backend files.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Src:
    source: str
    title: str
    content: str
    url: str
    author: str
    date: str
    region: str
    reliability: str
    tags: list[str]


# ---------- agriculture records, part 1 (apple .. cucumber) ----------
def _agriculture_records() -> dict[str, Src]:
    return {
        # ---------- APPLE ----------
        "apple": Src(
            "Penn State Extension (College of Agricultural Sciences)",
            "Apple Production",
            "Apple is a temperate tree fruit grown commercially across the world's mid-latitude regions and is one of the most economically important deciduous fruit crops. Production is concentrated where winters are cold enough to satisfy the chilling requirement, summers are moderate, and rainfall or irrigation is adequate; in the United States the leading regions are Washington state, New York, Michigan, Pennsylvania and California, while China is by far the world's largest producer, followed by the European Union, Turkey, India and the United States. Apples are grown on size-controlling rootstocks and trained to supported systems such as the tall spindle, which allow high-density plantings, earlier bearing and better fruit quality. Typical commercial orchard yields vary widely with density, rootstock, cultivar and management, ranging from roughly 400 to 1,000 bushels per acre in mature, well-managed blocks; yields are cyclical because the crop is biennial-bearing unless thinned and managed. Because apple is a perennial crop, rotation as practised in annual cropping does not apply: instead, orchard blocks are replanted on a long cycle, and growers manage soil health between blocks using cover crops and green manures, and reduce replant disease by rotating away from apples or by soil fumigation and rootstock choice before replanting. Grass and legume cover crops are widely used in orchard alleys to improve soil structure, support traffic and provide habitat for beneficial insects, while a herbicide strip is maintained in the tree row. Apples face significant climate-adaptation challenges, including spring frosts that damage bloom, hail damage, sunburn and increasingly variable winter chill; growers respond with frost protection, shade and evaporative cooling, sunburn protectants and the selection of cultivars matched to local chill and heat conditions. The crop also faces major pest and disease pressures including fire blight, apple scab, codling moth and the invasive spotted lanternfly, requiring integrated pest management.",
            "https://extension.psu.edu/apple-production",
            "Penn State Extension (College of Agricultural Sciences)",
            "2023-01-01", "north_america", "extension",
            ["apple", "temperate", "orchard", "production", "rootstock", "economics"],
        ),

        # ---------- BANANA ----------
        "banana": Src(
            "Food and Agriculture Organization of the United Nations (FAO)",
            "Banana Market Review and Commodity Overview",
            "Banana and plantain are among the most traded and most consumed fruits in the world and are a staple food and income source for millions of smallholders in tropical regions. The crop is grown throughout the humid tropics, principally within about 30 degrees of the equator, in warm, frost-free conditions with high and well-distributed rainfall or irrigation; the leading producers include India, China, Indonesia, Brazil, Ecuador, the Philippines and several Central American and Caribbean countries, while Ecuador, the Philippines, Colombia, Costa Rica and Guatemala are among the largest exporters. The trade is dominated by the Cavendish subgroup for export, while a very wide range of locally preferred cultivars and cooking bananas and plantains dominate domestic and regional markets in Africa, Asia and Latin America. Yields are highly variable: well-managed commercial plantations typically produce on the order of 30-50 tonnes per hectare per year, whereas smallholder stands commonly yield far less because of poor nutrition, pests and drought. Bananas are perennial and are grown in mats maintained by suckers rather than in annual rotation, but intercropping with annual food crops is common and cover crops and mulches are used to protect soil and conserve moisture; because the crop is propagated vegetatively, clean planting material is central to managing pests and diseases. The banana sector is under severe pressure from Fusarium wilt tropical race 4 (TR4) and from Black Sigatoka, both of which have reshaped production and driven investment in resistant varieties and strict biosecurity. Economic importance is high because bananas are the world's most exported fruit, an important source of foreign exchange for exporting countries and a critical source of nutrition and income for smallholder households. Climate adaptation focuses on drought-tolerant cultivars, irrigation, and diversification away from a single export cultivar.",
            "https://www.fao.org/markets-and-trade/commodities-overview/bananas-tropical-fruits/bananas/en",
            "Food and Agriculture Organization of the United Nations (FAO)",
            "2023-01-01", "global", "government",
            ["banana", "tropical", "traded-fruit", "TR4", "production", "fao"],
        ),

        # ---------- BASIL ----------
        "basil": Src(
            "Penn State Extension (College of Agricultural Sciences)",
            "Basil — Gardening Solutions",
            "Basil is a warm-season annual culinary herb in the mint family, grown both for fresh-market sales and for processing, and it occupies a fast-turnover niche in vegetable and herb production. It is native to tropical Asia and produced widely in warm, frost-free conditions under field culture, in high tunnels and in greenhouses, with the United States, Italy, Mexico, India and Egypt among the significant growing regions; in the United States basil is an important fresh-market herb and is also grown for pesto and dried herb products. Basil has a short production cycle — crops can be harvested only 30-60 days from transplanting and fields are often planted, cut and replanted or succession-sown through the frost-free season to maintain a steady supply, which makes it a good candidate for rotation with other short-season vegetables. UF/IFAS Gardening Solutions notes that basil grows best in full sun in rich, moist, well-drained soil and is best planted in the garden after the last frost, with pinch-pruning to keep plants bushy and productive. Typical fresh basil yields run on the order of several tonnes per hectare per cutting over a season, with high tunnel and greenhouse production achieving higher and more consistent yields and better leaf quality because the crop is protected from rain, wind and cold. Basil fits well into vegetable rotations and benefits from a preceding legume or a well-manured crop, and because it is harvested repeatedly for foliage it is a heavy nitrogen user; cover-cropping with grasses and legumes before planting helps build organic matter and manage nitrogen. Its production is economically attractive to small farms because the value per unit area is high, though the crop is perishable and requires careful post-harvest handling and rapid cooling. The principal production risks are downy mildew, which can devastate crops and is strongly weather-driven, and root and crown rots in poorly drained or overwatered soils; cultivar resistance to downy mildew has therefore become central to commercial variety choice, and climate adaptation focuses on protected culture and improved varieties.",
            "https://gardeningsolutions.ifas.ufl.edu/plants/edibles/vegetables/basil/",
            "UF/IFAS Extension (University of Florida)",
            "2023-01-01", "north_america", "extension",
            ["basil", "herb", "fresh-market", "downy-mildew", "protected-culture", "economics"],
        ),

        # ---------- BEAN ----------
        "bean": Src(
            "Penn State Extension (College of Agricultural Sciences)",
            "Snap Bean Production",
            "Snap beans (common bean harvested as a fresh or processed pod crop) are warm-season legumes grown across a wide range of temperate and subtropical environments and are an important vegetable crop in the United States and worldwide. Beans are grown as bush or pole types; bush beans dominate commercial fresh-market and processing production because they can be machine harvested, while pole beans are common in market-garden and home production. Because the common bean is a legume, it fixes atmospheric nitrogen when properly inoculated with the appropriate Rhizobium, which makes it a valuable rotation partner: succeeding crops such as leafy greens or brassicas benefit from the residual nitrogen and improved soil structure. Typical snap bean yields range broadly, on the order of several tonnes per hectare for well-managed commercial fields to much less in marginal conditions. Production is concentrated in regions with moderate summers, including the Midwest, the Pacific Northwest, New York and parts of the South for fresh market and processing, while major world producers of dry and snap beans include India, Myanmar, Brazil, China, Mexico and the United States. Beans fit readily into rotation with corn, root crops and brassicas and are well suited to cover-crop systems, where the crop itself acts as a nitrogen-fixing component of the rotation; growers commonly precede or follow beans with a cereal and legume cover crop mix to protect soil over winter. Climate-related risks include sensitivity to frost and cold, wet soils at planting, drought stress during pod fill and heat that causes pod abortion or poor pod set, so adaptation focuses on irrigation, planting-date adjustments and improved cultivars. Principal disease pressures include seed rots and seedling blights, common bacterial blight, rust, white mould and bean common mosaic virus, managed by clean seed, resistant varieties, rotation and timely irrigation.",
            "https://extension.psu.edu/snap-bean-production",
            "Penn State Extension (College of Agricultural Sciences)",
            "2023-01-01", "north_america", "extension",
            ["bean", "legume", "nitrogen-fixation", "rotation", "processing", "production"],
        ),

        # ---------- BELL PEPPER ----------
        "bell_pepper": Src(
            "Penn State Extension (College of Agricultural Sciences)",
            "Pepper Production",
            "Peppers are warm-season solanaceous vegetables, and bell and other sweet pepper types are an important fresh-market and processing crop grown across temperate and tropical regions worldwide. Peppers are grown both as field crops and under high tunnels, and they are widely grown in the open in warm, long-season regions; in the United States commercial production is concentrated in California, Florida, Georgia, Texas and the Southwest for fresh market, with additional acreage for processing and for protected-culture production that extends the season in cooler areas. Peppers grow on a wide range of soils but prefer well-drained, fertile ground with a pH for peppers of about 6.0-6.8, and they are commonly produced on polyethylene mulch with drip irrigation, which allows precise moisture and nutrient management and reduces fruit rot. Yields vary with type, region and management, ranging from several tonnes per hectare in field production to considerably higher in intensive, mulched and fertigated systems; bell pepper is a high-value crop per unit area, which makes it attractive for diversified vegetable farms. As a solanaceous crop, pepper shares diseases with tomato and other nightshades, so crop rotation away from solanaceous crops for at least two to three years is a core management practice; peppers rotate well with cereals, legumes and brassicas, and cover crops are used to build organic matter and suppress weeds before planting. Peppers are not frost tolerant and yields fall when temperatures are too cool or too hot, so adaptation relies choice, transplanting into warm soil, plasticulture to warm soil, shading in extreme heat and irrigation for drought. Principal disease and pest pressures include bacterial spot, phytophthora, powdery mildew, aphids and thrips, the latter important as virus vectors.",
            "https://extension.psu.edu/pepper-production",
            "Penn State Extension (College of Agricultural Sciences)",
            "2023-01-01", "north_america", "extension",
            ["bell-pepper", "solanaceous", "polyethylene-mulch", "rotation", "production", "economics"],
        ),

        # ---------- BLUEBERRY ----------
        "blueberry": Src(
            "Penn State Extension (College of Agricultural Sciences)",
            "Highbush Blueberry Production",
            "Blueberry is a perennial woody fruit crop of acid soils and is one of the most important small fruits traded internationally, with production expanding rapidly over the past few decades as fresh-market demand has grown. Commercial production is concentrated in regions with acid, well-drained, high-organic-matter soils and with enough winter chill for the type grown; the leading global producers include the United States, Chile, Peru, Spain, Mexico, Canada and Poland, and within the United States the principal states are Michigan, Georgia, Oregon, Washington, New Jersey and North Carolina. Penn State Extension explains that the blueberry plant is a long-lived perennial that can remain productive for 50 years or more with proper care, which makes pre-plant site selection and soil preparation decisive. Blueberry types differ by region: northern highbush dominates cooler regions, southern highbush the milder South, rabbiteye the Southeast, and lowbush the wild stands of Maine and eastern Canada; growers choose among early-, mid- and late-season cultivars to spread harvest and market risk. Penn State Extension notes that the United States once produced nearly all of the world's cultivated blueberries but now produces about 60 percent, reflecting major expansion in South America, Europe and elsewhere, while per capita consumption and demand for fresh berries have risen sharply. Blueberry plants require adequate moisture, particularly during fruit development, so irrigation is a key input; Penn State Extension stresses that after planting, adequate moisture is essential through the first year. Yields vary widely by type, age and management, from a few tonnes per hectare in young or low-input plantings to well over 10 tonnes per hectare in mature, intensive highbush blocks. Because blueberry is a long-lived perennial, rotation does not apply; instead, growers emphasise pre-plant pH correction with elemental sulfur, incorporation of organic matter and mulch, and cover crops between rows. The crop faces climate-adaptation challenges including insufficient winter chill, frost at bloom, hail and drought, and its principal disease and pest pressures include mummy berry, botryosphaeria canker, anthracnose fruit rot and spotted-wing drosophila.",
            "https://extension.psu.edu/highbush-blueberry-production",
            "Kathy Demchak, Senior Extension Associate, Penn State Extension (College of Agricultural Sciences)",
            "2023-02-01", "north_america", "extension",
            ["blueberry", "acid-soil", "highbush", "export", "production", "chilling"],
        ),

        # ---------- BROCCOLI ----------
        "broccoli": Src(
            "UF/IFAS Extension (University of Florida, Electronic Data Information Source)",
            "Chapter 6. Cole Crop Production (Vegetable Production Handbook of Florida)",
            "Broccoli is a cool-season cole crop grown for its edible head and is an important fresh-market and processing vegetable produced across temperate and subtropical regions worldwide. Because broccoli is adapted to cool growing conditions, commercial production is concentrated in areas with mild or cool seasons: in the United States the principal producing states are California and Arizona for year-round supply, with Florida, Georgia and other eastern states supplying winter and spring windows, and major world producers include China, India, the United States, Spain, Italy and Mexico. In Florida, cole crops including broccoli are grown as a winter vegetable crop on the state's sandy soils, and the Vegetable Production Handbook describes planting dates, cultivar recommendations and the pesticide options approved for the state, reflecting the crop's fit into a cool-season production window that avoids summer heat. Broccoli is grown from transplants and is commonly produced on raised, fumigated beds with drip irrigation; the crop matures in roughly 60-100 days depending on cultivar, season and region. Yields vary with region and management but quality commercial crops yield on the order of several tonnes per hectare per season, and broccoli is economically important both domestically and as an export and processing crop. Cole crops grow best on well-drained, fertile soils with pH near 6.0-6.8 and fit into rotation with non-brassica crops such as corn, legumes and root crops to reduce soil-borne disease including clubroot; cover crops are used to protect soil and break disease cycles. Climate-adaptation pressures include heat that causes bolting and poor head quality, so production is timed to cool windows and increasingly moved into protected culture, while principal pest pressures include lepidopteran caterpillars, aphids, flea beetles and diamondback moth.",
            "https://edis.ifas.ufl.edu/publication/CV122",
            "UF/IFAS Extension (University of Florida)",
            "2023-08-01", "north_america", "extension",
            ["broccoli", "cole-crop", "cool-season", "rotation", "production", "uf-ifas"],
        ),

        # ---------- CABBAGE ----------
        "cabbage": Src(
            "UF/IFAS Extension (University of Florida, Electronic Data Information Source)",
            "Chapter 6. Cole Crop Production (Vegetable Production Handbook of Florida)",
            "Cabbage is a cool-season cole crop grown for its dense head and is one of the most widely produced vegetables in the world, valued both as a fresh-market crop and for processing into sauerkraut and coleslaw. Cabbage production spans temperate and subtropical regions, with major world producers including China, India, Russia, South Korea, Ukraine, Japan and the United States; within the United States, production is concentrated in California, Texas, Florida, Georgia, New York and Wisconsin, with winter production in the South and summer production in northern states. In Florida, cabbage is grown as a winter vegetable crop on sandy soils and the Vegetable Production Handbook gives the state's planting dates, recommended cultivars and approved pesticide options. Cabbage grows on a wide range of soils but performs best on well-drained, fertile soil with pH near 6.0-6.8, and is usually grown from transplants on raised beds with drip irrigation; it is a heavy feeder and responds to good fertility and even moisture, and heads split if water is irregular near maturity. Yields are high for a vegetable, commonly on the order of 25-60 tonnes per hectare depending on region, cultivar and management, which makes cabbage an important and relatively low-cost source of nutrition and a significant commodity in world trade. As a brassica, cabbage should be rotated away from other cole crops to reduce clubroot and other soil-borne diseases, and it rotates well with cereals, legumes and non-brassica vegetables; cover crops improve soil health and reduce erosion. Climate adaptation centres on timing production to cool seasons and using protected culture and bolting-resistant cultivars where heat is a risk; principal pest pressures include caterpillars, aphids, flea beetles and root maggots.",
            "https://edis.ifas.ufl.edu/publication/CV122",
            "UF/IFAS Extension (University of Florida)",
            "2023-08-01", "north_america", "extension",
            ["cabbage", "cole-crop", "cool-season", "rotation", "production", "uf-ifas"],
        ),

        # ---------- CARROT ----------
        "carrot": Src(
            "UF/IFAS Extension (University of Florida, Electronic Data Information Source)",
            "Vegetable Production Handbook of Florida — Root and Bulb Crop Production",
            "Carrot is a cool-season root crop grown for its edible taproot and is one of the most important and most widely consumed root vegetables in the world, produced on every continent and traded extensively both fresh and processed. Production is concentrated in regions with cool to moderate growing conditions and deep, stone-free soils: in the United States the leading producing states are California and Washington for the fresh market and Wisconsin, Washington and the Pacific Northwest for processing, while major world producers include China, Uzbekistan, the United States, Russia, Ukraine, Poland and Turkey. Carrot is grown as an annual from direct-sown seed, and because the harvested product is the root, it demands a deep, friable, well-prepared seedbed; the crop is commonly grown on raised beds, and in Florida it is produced as a cool-season crop on the state's sandy soils, with planting dates, cultivar recommendations and approved pesticide options given in the Vegetable Production Handbook. Carrot yields are high, commonly on the order of 30-70 tonnes per hectare under good commercial management, and the crop is economically important as a low-cost, nutritious root vegetable and as a processing crop for freezing, canning and juice. Carrots fit well into rotation with cereals, legumes and brassicas, which helps break the cycles of soil-borne disease and nematodes, and cover crops are widely used to protect soil and add organic matter; because the crop is harvested mechanically, uniform soil conditions are important. Climate-adaptation considerations include heat, which reduces root quality and causes poor colour, and drought, which causes splitting and forking; principal pest and disease pressures include carrot rust fly, carrot weevil, aster yellows, alternaria and cavity spot.",
            "https://edis.ifas.ufl.edu/publication/CV100",
            "UF/IFAS Extension (University of Florida)",
            "2023-08-01", "north_america", "extension",
            ["carrot", "root-crop", "cool-season", "rotation", "production", "uf-ifas"],
        ),

        # ---------- CAULIFLOWER ----------
        "cauliflower": Src(
            "UF/IFAS Extension (University of Florida, Electronic Data Information Source)",
            "Chapter 6. Cole Crop Production (Vegetable Production Handbook of Florida)",
            "Cauliflower is a cool-season cole crop grown for its edible curd and is the most exacting and least widely adapted of the commercially important brassicas. Production is concentrated in regions with long, cool, evenly moist growing seasons, and because the crop is sensitive to heat it is grown mostly in coastal and temperate areas: the leading producing countries include China, India, Spain, Mexico, Italy, France and the United States, while within the United States California dominates production with additional acreage in Arizona, New York and other states and winter production in Florida and Texas. In Florida, cauliflower is grown as a winter cole crop on sandy soils, and the Vegetable Production Handbook gives the crop's planting dates, recommended cultivars and approved pesticide options. Cauliflower is grown from transplants on well-prepared, fertile, well-drained beds with drip irrigation, and it has a high nutrient and water demand and no tolerance for stress: nutrient or moisture shortage at curd initiation causes buttoning and small, poor-quality curds, and the curd must be protected from sunlight by tying the wrapper leaves over the head. Yields are lower and more variable than cabbage or broccoli, commonly on the order of 10-30 tonnes per hectare, but the crop is high-value in fresh markets and increasingly important as a component of the processed and frozen vegetable trade and as a low-carbohydrate food. As a cole crop, cauliflower must be rotated away from other brassicas to manage clubroot and other soil-borne diseases, and it rotates well with cereals, legumes and non-brassica vegetables; cover cropping supports soil health and reduces erosion. Climate adaptation is essentially a matter of timing to cool seasons; principal pest pressures include caterpillars, aphids, flea beetles and root maggots.",
            "https://edis.ifas.ufl.edu/publication/CV122",
            "UF/IFAS Extension (University of Florida)",
            "2023-08-01", "north_america", "extension",
            ["cauliflower", "cole-crop", "cool-season", "rotation", "production", "uf-ifas"],
        ),

        # ---------- CELERY ----------
        "celery": Src(
            "UF/IFAS Extension (University of Florida, Electronic Data Information Source)",
            "Chapter 1. Commercial Vegetable Production in Florida (Vegetable Production Handbook of Florida)",
            "Celery is a cool-season vegetable grown for its crisp petioles and is a relatively specialised crop with a long growing season, a shallow root system and a narrow set of adapted production regions. Commercial production is concentrated where the climate is cool and moist: in the United States the dominant producing state is California, with additional production in Florida, Michigan, Texas and Ohio, while the major world producers include the United States, Spain, Mexico, China, India, Italy and the Netherlands. UF/IFAS's Vegetable Production Handbook presents comprehensive vegetable production guidance for Florida, covering the general production practices, cultivar choice and pesticide options that apply across the state's commercial vegetable crops, of which celery is an established cool-season component grown on the state's sandy soils with raised, well-prepared beds and drip irrigation. Celery requires a fertile, high-organic-matter soil and a long, cool season that allows the crop to mature without heat stress; it needs a high, continuous supply of water and nutrients because the harvested product is the swollen petiole and any interruption of growth reduces quality and causes physiological disorders. Yields are high for a vegetable, with quality commercial crops commonly yielding on the order of 40-70 tonnes per hectare, and the crop is economically important both for the fresh market and for processing into soup, juice and dried products, and as a flavour base in many food products. Celery is normally rotated with non-apiaceous crops — it should not follow other members of the carrot family such as carrot or parsley, because of shared soil-borne disease and nematode problems — and it fits into rotation with cereals, legumes and brassicas, with cover crops used to build organic matter and protect soil. Climate-adaptation pressures include heat, which causes pithy, stringy and poorly flavoured petioles, and the crop requires irrigation or even evaporative cooling in hot conditions; principal disease pressures include aster yellows, fusarium yellows, septoria leaf blight, pink rot and celery mosaic virus.",
            "https://edis.ifas.ufl.edu/publication/CV100",
            "UF/IFAS Extension (University of Florida)",
            "2023-08-01", "north_america", "extension",
            ["celery", "cool-season", "shallow-rooted", "rotation", "production", "uf-ifas"],
        ),

        # ---------- CHERRY ----------
        "cherry": Src(
            "Penn State Extension (College of Agricultural Sciences)",
            "Fruit Production and Harvesting — Tree Fruit",
            "Cherry is a temperate stone fruit grown as both sweet cherries, which are eaten mostly fresh, and tart (sour) cherries, which are mainly processed for pies, juice and preserves. Cherry production is limited to regions with cold winters, moderate summers and adequate chill and, critically, sites that avoid spring frost, because the crop blooms early and the flowers and young fruit are highly vulnerable to frost. Penn State Extension's fruit production guidance stresses that site selection is the first and most important decision, because most fruit crops need plenty of sunlight through the day to produce well, and that orchard soil should be tested and amended before planting since correction afterwards is slow and difficult. The major world producers include Turkey, the United States, Russia, Poland, Ukraine, Iran, Italy and Chile, while in the United States sweet cherries are dominated by Washington, California and Oregon and tart cherries by Michigan and Wisconsin. Sweet cherries require cross-pollination with a compatible polleniser cultivar and are increasingly grown on dwarfing rootstocks in high-density plantings, which Penn State Extension recommends for home and small-scale plantings because rootstocks keep trees manageable for pruning, spraying and harvest and bring them into bearing sooner; tart cherries are frequently self-fruitful. Yield varies widely with type, age, rootstock and region, ranging from a few tonnes per hectare in young or low-density blocks to substantially more in mature, well-managed high-density orchards. As a perennial crop, cherry is not rotated annually; instead, orchard blocks are managed on long cycles, with cover crops and resident grass or legume alleys used to maintain soil health, support machinery and provide habitat for beneficials. Cherry is economically important for fresh export and for the processing industry, and its fruit commands premium prices when quality is high. Climate-adaptation challenges include spring frost, rain-induced fruit cracking, insufficient winter chill and heat stress; principal disease and pest pressures include brown rot, cherry leaf spot, black knot, cherry fruit fly and spotted-wing drosophila.",
            "https://extension.psu.edu/forage-and-food-crops/fruit/production-and-harvesting",
            "Jayson K. Harper, Ph.D., Tara Baugher, Ph.D., and Melanie Schupp, Penn State Extension",
            "2023-01-01", "north_america", "extension",
            ["cherry", "temperate", "stone-fruit", "frost-risk", "processing", "production"],
        ),

        # ---------- CITRUS ----------
        "citrus": Src(
            "Food and Agriculture Organization of the United Nations (FAO)",
            "Citrus — Food and Agriculture Market Analysis (FAMA)",
            "Citrus is grown in tropical and subtropical regions across more than 140 countries and is among the most important and most traded fruit groups in the world, comprising oranges, tangerines and mandarins, lemons and limes, grapefruit and other citrus. FAO notes that citrus fruit production is a major activity in several countries and that citrus is one of the leading traded fruits globally, with about half of global production entering international trade and a very large share of production going to processing for juice. The crop is adapted to warm subtropical and Mediterranean climates with mild winters and adequate irrigation, and production is concentrated in regions free of severe frost: the major producers include Brazil, China, India, the United States, Mexico, Spain, Egypt, Turkey, South Africa and Argentina, with Brazil and the United States historically dominant in orange production. FAO highlights the nutritional importance of citrus: it is one of the most important commercial sources of vitamin C and also supplies folate, potassium and dietary fibre, and it is a recommended component of diets aimed at preventing chronic disease, which underpins its economic importance both as a fresh fruit and as a processed product. Oranges are the largest component of the crop by volume, with a large share going to juice, while tangerines and mandarins have grown fastest in fresh trade and lemons and limes are significant for both fresh and processing markets. Yields vary by species, region and management but commonly reach on the order of 20-40 tonnes per hectare in well-managed mature groves. Citrus trees are perennial and evergreen, grown on long rotations with rootstock choice central to managing soil-borne disease; cover crops and mulches are used between rows and in the grove to improve soil health and reduce erosion. The sector faces serious climate and pest challenges: citrus greening or HLB has devastated production in Florida and parts of the Americas and Asia and has reshaped production, while freeze events, drought and heat affect yield and quality, driving adaptation through resistant rootstocks, protected culture and geographic shifts.",
            "https://www.fao.org/markets-and-trade/commodities-overview/food-and-agriculture-market-analysis-(FAMA)/citrus/en",
            "Food and Agriculture Organization of the United Nations (FAO)",
            "2023-01-01", "global", "government",
            ["citrus", "subtropical", "oranges", "vitamin-c", "trade", "fao"],
        ),

        # ---------- COFFEE ----------
        "coffee": Src(
            "Food and Agriculture Organization of the United Nations (FAO)",
            "Coffee Commodity Overview",
            "Coffee is one of the most widely traded agricultural commodities in the world and is grown in the tropical and subtropical highlands of Africa, Asia and Latin America, principally by smallholders. Production is concentrated where temperatures are moderate and rainfall is well distributed, typically at elevations of roughly 600-2,000 metres depending on species and latitude; arabica, which dominates the higher-quality trade, prefers cooler highland conditions, while robusta is grown at lower elevations and is more heat and disease tolerant. The leading producers include Brazil, Vietnam, Colombia, Indonesia and Ethiopia, with Brazil and Vietnam together accounting for a very large share of world supply, and other significant producers across Central America, Africa and Asia. Yields vary widely with system, species, elevation and management, commonly reaching on the order of 1-3 tonnes per hectare of green coffee in well-managed plantations and considerably less in low-input smallholder stands. Coffee is a perennial tree crop managed on long cycles through pruning and rejuvenation rather than annual rotation; shade trees are widely used to moderate temperature, improve soil and diversify income, and cover crops and mulch are used to protect soil on sloping land. The crop is economically vital: it is a major source of foreign exchange for producing countries and supports the livelihoods of an estimated 25 million smallholder households, and it is one of the most valuable exports of many developing economies. The sector faces acute climate-adaptation pressure because the crop is sensitive to rising temperatures, changing rainfall and drought, which are already shifting suitable production zones and driving adaptation through shade management, irrigation, resistant varieties and migration of production to higher elevations; coffee leaf rust has caused severe losses in Central America and elsewhere, and pests including the coffee berry borer remain major constraints.",
            "https://www.fao.org/markets-and-trade/commodities-overview/beverages/coffee/en",
            "Food and Agriculture Organization of the United Nations (FAO)",
            "2023-01-01", "global", "government",
            ["coffee", "tropical-highland", "arabica", "robusta", "smallholder", "fao"],
        ),

        # ---------- CORN ----------
        "corn": Src(
            "USDA Economic Research Service (United States Department of Agriculture)",
            "Crops — Corn and Other Feed Grains",
            "Corn (maize) is the largest crop by volume in the United States and one of the most important cereal crops in the world, used for animal feed, food, ethanol and industrial products, and it dominates the agricultural landscape of the U.S. Midwest. USDA's Economic Research Service notes that the U.S. feed grain sector — corn, sorghum, barley and oats — is the largest segment of U.S. field crops, representing nearly one-third of all cash receipts for field and miscellaneous crops, nearly one-third of area planted to principal crops, and about one-tenth of U.S. agricultural export value, and that corn's use as an ethanol feedstock has reshaped U.S. feed-grain demand and markets. Corn is a warm-season crop adapted to a wide range of temperate and subtropical environments, and in the United States the leading producing states form the Corn Belt — Iowa, Illinois, Nebraska, Minnesota, Indiana, Kansas, Missouri and South Dakota — with additional production in the Great Lakes, Plains and eastern states; globally the leading producers are the United States, China, Brazil, the European Union, Argentina, Ukraine and India. Corn production is highly concentrated in rainfed regions that receive adequate summer rainfall, with irrigation important in areas such as Nebraska and Kansas, and yields vary widely with region, hybrid and management: irrigated and high-yield rainfed areas in the U.S. Corn Belt commonly reach on the order of 11-13 tonnes per hectare, while average global yields are much lower. Corn is an outstanding rotation partner and is almost always grown in rotation with soybean, which supplies nitrogen by fixation and breaks pest and disease cycles; corn ground is also widely planted to cereal rye and other cover crops over winter to protect soil and reduce erosion and nitrate loss. Corn is economically central to U.S. agriculture and to the economies of producing regions, underpinning the livestock, ethanol and food industries, and it is also a major export commodity for the United States, Brazil, Argentina and Ukraine. Climate-adaptation pressures include drought, heat during pollination (which sharply reduces yield), changes in growing-season length and increasing rainfall extremes; principal pest and disease pressures include the European corn borer, corn rootworm, corn earworm, and foliar and ear diseases such as grey leaf spot and mycotoxin-producing ear rots.",
            "https://www.ers.usda.gov/topics/crops",
            "USDA Economic Research Service (United States Department of Agriculture)",
            "2023-01-01", "north_america", "government",
            ["corn", "maize", "corn-belt", "soybean-rotation", "ethanol", "usda-ers"],
        ),

        # ---------- CUCUMBER ----------
        "cucumber": Src(
            "UF/IFAS Extension (University of Florida, Electronic Data Information Source)",
            "Chapter 7. Cucurbit Production (Vegetable Production Handbook of Florida)",
            "Cucumber is a warm-season cucurbit grown for fresh-market and processing use and is produced throughout the temperate and subtropical world, most commonly under protected or mulched systems that manage moisture and disease. Cucumbers are grown both in the open and in high tunnels and greenhouses, with the latter increasingly important for fresh-market supply; production requires warm conditions and is limited by frost and by cool weather, which causes poor fruit set and misshapen fruit. In Florida, cucumbers are grown as a cool- or warm-season cucurbit crop on sandy soils, and the Vegetable Production Handbook gives the state's planting dates, cultivar recommendations and approved pesticide options for cucurbits. In the United States, commercial production is concentrated in Florida, Georgia, California, Michigan, New York, Indiana and the Carolinas, with substantial processing acreage; major world producers include China, Turkey, Russia, Mexico, the United States, Ukraine, Iran and Spain. Cucumbers are typically grown on raised, often fumigated beds with drip irrigation and plastic mulch, which keep the crop above cool soil, retain moisture and reduce fruit rot, and yields are high in well-managed crops, commonly on the order of 20-50 tonnes per hectare under field-polyculture and considerably higher in greenhouse production. Cucurbits share pest and disease problems and should be rotated away from other cucurbits, alternating with cereals, legumes and non-cucurbit vegetables to break disease cycles, and cover crops are used before planting to manage soil and increase organic matter. The crop is economically important both fresh and processed — including pickling — and its production risks include downy and powdery mildew, bacterial wilt vectored by cucumber beetles, and aphids transmitted virus; adaptation centres on protected culture, mulching and resistant cultivars.",
            "https://edis.ifas.ufl.edu/publication/CV123",
            "UF/IFAS Extension (University of Florida)",
            "2023-08-01", "north_america", "extension",
            ["cucumber", "cucurbit", "mulch", "rotation", "production", "uf-ifas"],
        ),
    }


# ---------- agriculture records, part 2 (eggplant .. grapevine) ----------
def _agriculture_records_2() -> dict[str, Src]:
    return {
        # ---------- EGGPLANT ----------
        "eggplant": Src(
            "UF/IFAS Extension (University of Florida, Electronic Data Information Source)",
            "Chapter 8. Eggplant Production (Vegetable Production Handbook of Florida)",
            "Eggplant is a warm-season solanaceous fruit vegetable grown for fresh market and, to a lesser extent, processing, and it is produced throughout the tropical and temperate world wherever a long, warm season is available. It is more heat-tolerant than tomato or pepper and is well suited to warm regions, with major world producers including China, India, Egypt, Turkey, Iran, Italy and Indonesia; in the United States commercial production is concentrated in Florida, California, Georgia, New Jersey and Texas, with Florida and other southern states supplying winter and spring windows. The Vegetable Production Handbook gives Florida's recommended eggplant production practices, including cultivar choice, planting dates and the pesticide options approved for the state. Eggplant grows best on well-drained, fertile soil with adequate organic matter and is very commonly produced on raised, fumigated beds with plastic mulch and drip irrigation, which warms the soil, controls moisture and reduces fruit rot; the crop is grown from transplants and requires a long frost-free season to bear its full yield. Yields vary with system and region, commonly on the order of 20-40 tonnes per hectare in well-managed field production, and the crop is economically important as a fresh-market vegetable with strong demand in Mediterranean, Middle Eastern, Asian and specialty markets. As a solanaceous crop, eggplant should be rotated away from tomato, pepper and potato for at least two to three years to reduce soil-borne diseases including verticillium wilt and to break pest cycles, and it rotates well with cereals, legumes and brassicas; cover crops build organic matter. Climate adaptation relies on warm-season timing, plasticulture and irrigation, and the principal pest pressures include flea beetles, Colorado potato beetle, aphids, spider mites and eggplant fruit and shoot borer.",
            "https://edis.ifas.ufl.edu/publication/CV124",
            "UF/IFAS Extension (University of Florida)",
            "2023-08-01", "north_america", "extension",
            ["eggplant", "solanaceous", "heat-loving", "rotation", "production", "uf-ifas"],
        ),

        # ---------- GARLIC ----------
        "garlic": Src(
            "Penn State Extension (College of Agricultural Sciences)",
            "Garlic Production",
            "Garlic is a cool-season allium grown for its bulbs and is produced on every continent, both for culinary use and, increasingly, for nutraceutical markets. Garlic is grown almost entirely from cloves rather than true seed, and it is classified into hardneck and softneck types: hardneck types are more cold-hardy and are grown in northern regions, while softneck types, which store better and braid well, dominate warmer production areas, including the major California production of the United States. Global garlic production is dominated by China, which accounts for the large majority of world supply, followed by India, Bangladesh, Egypt, Spain, South Korea and the United States; within the United States, commercial production is concentrated in California, with significant regional production in New York, Oregon, Washington and elsewhere to serve local fresh markets. Garlic is typically planted in the autumn in cold-winter regions so that roots establish before the ground freezes, and in spring in milder regions or for certain types, and it is grown from cloves planted at relatively close spacing, typically several inches apart in multiple rows per bed; yields are commonly on the order of 5-12 tonnes per hectare under good commercial management. The crop fits well into vegetable rotation because it is planted in autumn and harvested in mid-summer, leaving the ground available for a succeeding crop, and it can follow a legume or a heavily manured crop; because alliums are intolerant of waterlogging and are poor competitors, cover crops and careful soil preparation are used to improve structure and suppress weeds. Garlic is economically important as a high-value fresh market vegetable and because it is widely processed and traded internationally, and its production risks include onion thrips, white rot, fusarium basal rot and stem and bulb nematode, with climate adaptation focused on type choice and planting-date adjustment.",
            "https://extension.psu.edu/garlic-production",
            "Penn State Extension (College of Agricultural Sciences)",
            "2023-01-01", "north_america", "extension",
            ["garlic", "allium", "hardneck", "softneck", "rotation", "production"],
        ),

        # ---------- GINGER ----------
        "ginger": Src(
            "Food and Agriculture Organization of the United Nations (FAO)",
            "Tropical Root and Tuber Crops — Ginger Production and Utilisation",
            "Ginger is a herbaceous perennial grown as an annual crop for its aromatic rhizome and is produced throughout the humid tropics and subtropics, where it is an important cash crop and a widely used spice and medicinal plant. Production is concentrated in warm, humid regions with well-distributed rainfall: the major producers include India, China, Nigeria, Nepal, Indonesia, Thailand and, in the Americas, Brazil, Peru and Jamaica, and ginger is traded internationally in fresh, dried, powdered, pickled and essential-oil forms. Ginger is propagated vegetatively from seed rhizomes rather than true seed, and this makes clean, disease-free planting material a central production requirement; the crop requires a long, warm, frost-free growing season, typically spanning most of a year, and is grown on well-drained, fertile soils high in organic matter, usually on raised beds or ridges with heavy mulching. Yields vary widely with system, cultivar and region, commonly on the order of 15-30 tonnes per hectare of fresh rhizome under good management but considerably less in low-input systems. Ginger fits well into tropical rotations and mixed cropping systems, where it is often grown with other cash and food crops, and the long fallow periods traditionally used in ginger-growing areas are important for managing soil-borne disease and soil fertility, while mulches and cover crops protect soil on sloping ground and return organic matter. The crop is economically significant as a smallholder cash crop, a source of export revenue and a widely traded commodity, and its production risks include bacterial wilt, rhizome rots, fusarium yellows, nematodes and the shoot borer, all of which are worsened by poor drainage and by reusing infected seed, so adaptation centres on clean seed, rotation and drainage.",
            "https://www.fao.org/4/t0207e/T0207E01.htm",
            "Food and Agriculture Organization of the United Nations (FAO)",
            "2015-11-04", "global", "government",
            ["ginger", "rhizome", "tropical", "smallholder", "rotation", "fao"],
        ),

        # ---------- GRAPE ----------
        "grape": Src(
            "USDA Economic Research Service (United States Department of Agriculture) / Penn State Extension",
            "Fruit and Tree Nuts — Grape Production",
            "Grape is a temperate and subtropical perennial vine grown for fresh table fruit, raisins and, above all, wine, and it is one of the highest-value fruit crops in the world. Grapes are adapted to Mediterranean and continental climates with warm, dry summers and cool winters, and production is heavily concentrated in a small number of regions: the largest world producers include China, Italy, Spain, France, the United States, Turkey and Argentina, with wine-grape production concentrated in Europe and the Americas and table-grape and raisin production concentrated in Turkey, India, the United States and Chile. In the United States, commercial grape production is dominated by California for both wine and table grapes, with significant juice-grape production in New York, Pennsylvania, Washington and Michigan. Yields vary enormously with type, region and management, ranging from a few tonnes per hectare in premium wine-grape blocks, where yield is deliberately restricted to improve quality, to 20-30 tonnes per hectare or more in high-yielding table and raisin vineyards. Grape is a long-lived perennial grown on a trellis and managed by annual dormant pruning that sets the crop for the coming season; because it is a perennial crop, rotation as practised in annual cropping does not apply, but growers use cover crops between rows and resident vegetation to protect soil, reduce erosion, support machinery and improve soil biology. Grapes command very high value per hectare and the wine sector is economically important to many rural economies and to international trade, while the table-grape and raisin sectors are significant export commodities. Climate-adaptation pressures include drought, heat and smoke taint from wildfires, and shifts that are already moving suitable wine-grape production zones; principal pest and disease pressures include powdery and downy mildew, black rot, grape berry moth, phylloxera and, in some regions, Pierce's disease and the glassy-winged sharpshooter.",
            "https://www.ers.usda.gov/topics/crops/fruit-tree-nuts/",
            "USDA Economic Research Service (United States Department of Agriculture)",
            "2023-01-01", "north_america", "government",
            ["grape", "vineyard", "wine", "table-grape", "perennial", "usda-ers"],
        ),

        # ---------- GRAPEVINE ----------
        "grapevine": Src(
            "Penn State Extension (College of Agricultural Sciences)",
            "Backyard Grape Growing",
            "Grapevine is a long-lived, woody, climbing perennial and is one of the most ancient cultivated crops, grown on trellises or other supports in vineyards and, on a small scale, on arbors and fences. Vines are adapted to warm, dry summers and require good air drainage and sun exposure; Penn State Extension notes that a well-established grapevine adapted to its climate will produce fruit for many decades, which makes planting and training decisions long-lasting. Commercial grapevine culture is dominated by a few world regions for wine and table grapes, with China, Italy, Spain, France, the United States, Turkey and Argentina among the leading producers, while smaller plantings are found wherever suitable climate exists. The grapevine's growth habit is distinctive and determines its management: because grapes bear fruit on one-year-old wood, the vine must be trained to a permanent trunk and cordon or head system and then pruned each dormant season to set the bud number and therefore the crop. Penn State Extension explains that a mature grapevine naturally produces far more wood than it can support — much more than is necessary or desirable — and that typically about 90 percent of the new growth of a mature vine is removed during dormant pruning, most of it in the dormant months between December and March; balanced pruning in which roughly three to four buds are retained per foot of cordon matches the vine's vigour to its crop. Vines can be trained to a commercial trellis, an arbor or a fence, and the training system should be decided early because there is only one chance to train the vine correctly. Grapevines are grown on long rotations rather than annual ones, and cover crops between rows protect the soil, reduce erosion and support soil biology. Production risks include the mildews, black rot, berry moths and phylloxera, and climate adaptation centres on site selection, irrigation in dry regions and cultivar choice.",
            "https://extension.psu.edu/backyard-grape-growing/",
            "Barbara Goulart and Mark Chien, Penn State Extension (College of Agricultural Sciences)",
            "2023-05-11", "north_america", "extension",
            ["grapevine", "perennial", "trellis", "pruning", "vineyard", "production"],
        ),
    }


# ---------- agriculture records, part 3 (lettuce .. rice) ----------
def _agriculture_records_3() -> dict[str, Src]:
    return {
        # ---------- LETTUCE ----------
        "lettuce": Src(
            "UF/IFAS Extension (University of Florida, Electronic Data Information Source)",
            "Chapter 9. Leafy Vegetable Production (Vegetable Production Handbook of Florida)",
            "Lettuce is a cool-season leafy vegetable grown for fresh-market salads and is one of the most important high-value vegetable crops in the world, produced on every continent and traded extensively both domestically and internationally. Commercial production is concentrated in cool coastal and temperate regions with mild temperatures: in the United States the dominant producing region is California, especially the Salinas and Imperial Valleys, with Arizona producing a large winter crop and Florida and other states contributing seasonal supply; the major world producers include China, the United States, India, Spain and Italy. Lettuce is produced as crisphead, romaine, leaf and butterhead types, and the type grown is closely tied to market and region. In Florida, leafy vegetables including lettuce are grown as cool-season crops on the state's sandy soils, and the Vegetable Production Handbook gives planting dates, cultivar recommendations and approved pesticide options for the state. Lettuce is a shallow-rooted crop with a short production cycle, grown from transplants or direct-seeded and commonly produced on raised beds with drip irrigation; it requires high, steady inputs of water and nutrients because the harvested product is the leaf and quality falls quickly under stress. Yields are high and the crop turns over rapidly, commonly producing on the order of 20-40 tonnes per hectare per crop with multiple crops per year in favourable regions, which contributes to its economic importance as a fresh-market salad crop and to its significance in diets. Lettuce is rotated with non-lettuce crops, including brassicas, root crops, cereals and legumes, to break disease cycles; cover crops improve soil health. Climate-adaptation pressures are acute because lettuce is sensitive to heat, which causes bolting, bitterness and tipburn, and production is already shifting and being protected by coastal fog belts, high tunnels and improved cultivars; principal disease and pest pressures include downy mildew, sclerotinia, aphids, thrips and leafminers.",
            "https://edis.ifas.ufl.edu/publication/CV293",
            "UF/IFAS Extension (University of Florida)",
            "2023-08-01", "north_america", "extension",
            ["lettuce", "leafy-vegetable", "cool-season", "rotation", "production", "uf-ifas"],
        ),

        # ---------- MAPLE ----------
        "maple": Src(
            "University of Minnesota Extension (College of Food, Agricultural and Natural Resource Sciences)",
            "Homemade Maple Syrup",
            "Maple syrup production is based on the sap of sugar, black, red and silver maples and is a distinctive seasonal agro-forestry enterprise in the northeastern United States and eastern Canada, where it is economically and culturally important. UMN Extension notes that four species of maple can be used for sap production in Minnesota, with sugar maple the popular choice for its sweet sap; the sugar maple is the state tree of several states and dominates commercial syrup production, while red maple and boxelder are used where sugar maple is scarce. Maple syrup production is concentrated in the northern United States and eastern Canada, with Quebec by far the largest producer, followed by Vermont, Maine, New York, Ontario, Wisconsin and New Hampshire; collectively these regions supply the great majority of the world's syrup and are the source of a substantial export trade. The resource is managed as woodland rather than as an annual crop rotation: for best sap production a tree should have a short trunk topped with abundant foliage, and UMN Extension stresses that the key to good grove management is cutting practices that favour the development and retention of such trees, which makes sustainable forest management central to the enterprise. Tapping is done in late winter: UMN Extension advises completing tapping by mid-February in central and southern Minnesota and by the second week of March in the northern part of the state, and tapping only trees at least 10 inches in diameter at 4 feet above the ground, with no more than two taps in trees greater than 20 inches. Sap runs when a rapid warming trend follows a freezing night, and a single taphole normally yields between one quart and one gallon of sap per flow period, accumulating 10-12 gallons in a season. Climate change is a serious adaptation concern because syrup production depends on the freeze-thaw cycle, and warming winters are altering the timing and length of the sap season and shifting the suitable range of sugar maple northward; production risks also include forest pests and diseases such as the Asian longhorned beetle and sugar maple decline.",
            "https://extension.umn.edu/gathering-wild-grown-plants-and-fungi/homemade-maple-syrup",
            "University of Minnesota Extension (CFANS)",
            "2023-01-01", "north_america", "extension",
            ["maple", "syrup", "agroforestry", "sugar-maple", "climate", "umn"],
        ),

        # ---------- PEACH ----------
        "peach": Src(
            "Food and Agriculture Organization of the United Nations (FAO) / Penn State Extension",
            "Fruit Production and Harvesting — Tree Fruit and Stone Fruit",
            "Peach and nectarine are temperate stone fruits grown for fresh market, processing (canning and freezing) and, increasingly, for export, and they are among the most widely planted deciduous fruit crops in the world. Peaches require a distinct winter chilling period to break dormancy and bud normally, so production is concentrated in regions with cold but not severe winters and warm summers; because the trees bloom relatively early, suitable sites must also avoid spring frosts that destroy the crop. Penn State Extension's fruit production guidance stresses that site selection is the first and most important decision, because most fruit crops need plenty of sunlight through the day to produce well, and that orchard soil should be tested and amended before planting since correction afterwards is slow and difficult. The major world producers include China, which dominates world production, along with Spain, Italy, Turkey, Greece, the United States and Iran; in the United States, California dominates canning clingstone production while Georgia, South Carolina, New Jersey, Pennsylvania and other states produce fresh-market fruit. Peach production is organised around thinning and pruning as crop-load management: Penn State Extension notes that fruit trees often set more fruit than they can support, that leaving too much fruit weakens the tree and makes it more susceptible to pests, and that thinning is a highly effective crop-load management tool that improves fruit size, reduces disease spread and promotes return bloom, while pruning develops the desired tree shape, improves air circulation and increases produce quality. Yields vary by region, age and management, commonly reaching on the order of 15-30 tonnes per hectare in mature, well-managed orchards. Peach is a perennial, so rotation does not apply; instead, orchard blocks are managed on long cycles with cover crops and grass or legume alleys supporting soil health. Climate-adaptation pressures include insufficient winter chill, spring frost and hail; principal disease and pest pressures include brown rot, bacterial spot, peach leaf curl, oriental fruit moth and plum curculio.",
            "https://extension.psu.edu/forage-and-food-crops/fruit/production-and-harvesting",
            "Jayson K. Harper, Ph.D., Tara Baugher, Ph.D., and Melanie Schupp, Penn State Extension",
            "2023-01-01", "north_america", "extension",
            ["peach", "stone-fruit", "chilling", "thinning", "production", "processing"],
        ),

        # ---------- PLUM ----------
        "plum": Src(
            "Penn State Extension (College of Agricultural Sciences)",
            "Fruit Production and Harvesting — Tree Fruit and Stone Fruit",
            "Plum and prune are temperate stone fruits grown for fresh market, drying and processing, and they are important both as a fresh fruit and as a dried commodity in world trade. Plums are grouped into Japanese types, which are generally larger, softer and suited to fresh market, and European types, which are firmer and are the principal source of prunes and processed products. Production is concentrated in regions with adequate winter chilling and moderate summers: the leading world producers include China, Romania, Serbia, the United States, Turkey, Italy, Spain and Chile, and within the United States commercial plum production is dominated by California, with additional production in Michigan, Oregon, Washington and the Pacific Northwest for fresh and processed markets. Penn State Extension's fruit production guidance stresses that site selection and pre-plant soil testing are decisive, because most fruit crops need plenty of sunlight through the day to produce well and because established trees are difficult to correct. Penn State Extension describes pruning and thinning as the central crop-management practices for tree fruit: fruit trees often set more fruit than they can support, and leaving too much fruit weakens the tree and makes it more susceptible to pests, so thinning improves fruit size, reduces disease spread and promotes return bloom, while pruning develops the desired tree shape, improves air circulation and increases produce quality. Yields vary by type, region, age and management, commonly reaching on the order of 10-25 tonnes per hectare in mature, well-managed orchards. As a perennial crop, plum is not rotated annually; instead orchard blocks are managed on long cycles with cover crops and grass or legume alleys supporting soil health. Production risks include black knot, brown rot, bacterial spot and plum curculio, and climate adaptation centres on cultivar choice matched to local chill, frost avoidance and irrigation.",
            "https://extension.psu.edu/forage-and-food-crops/fruit/production-and-harvesting",
            "Jayson K. Harper, Ph.D., Tara Baugher, Ph.D., and Melanie Schupp, Penn State Extension",
            "2023-01-01", "north_america", "extension",
            ["plum", "stone-fruit", "prune", "thinning", "production", "processing"],
        ),

        # ---------- POTATO ----------
        "potato": Src(
            "UF/IFAS Extension (University of Florida, Electronic Data Information Source)",
            "Chapter 14. Potato Production (Vegetable Production Handbook of Florida)",
            "Potato is the world's most important non-cereal food crop and one of the most widely grown and traded vegetables, produced across temperate, subtropical and tropical highland regions and consumed fresh and in processed forms such as chips, fries and dehydrated products. Potatoes are adapted to cool growing conditions and are grown in two main production systems: a summer crop in temperate regions with a single growing season, and winter and spring crops in warm-climate regions where potatoes are grown during the cooler months. The major world producers include China, India, Russia, Ukraine, the United States, Germany, Bangladesh and Poland, while in the United States production is concentrated in Idaho, Washington, Wisconsin, North Dakota, Maine and Colorado for processing and fresh market, with significant winter and spring production in Florida and Texas. UF/IFAS's Vegetable Production Handbook describes potato production in Florida as a winter and spring crop: potatoes are grown in all 50 states, but the Florida crop is planted in spring in the Hastings area of St. Johns, Flagler and Putnam counties, where half the crop is used for chips, and in winter to the south near Immokalee for table stock. The chapter gives planting dates, cultivar recommendations, and the yield and specific-gravity classes by which potatoes are graded, with total yields classed as high above 300 cwt per acre, medium-high 250-299, medium 200-249 and low-medium 150-199, and tuber specific gravity classed as high above 1.075 and low below 1.064. Potato is grown as an annual from certified seed tubers on well-drained, friable soils, commonly on raised beds and increasingly under irrigation; certified seed is central because potatoes are propagated vegetatively and seed-borne disease reduces yield and marketability. Potatoes fit well into rotation with cereals, legumes and brassicas, and rotation away from other solanaceous crops and other potatoes is a core practice for managing soil-borne disease including nematodes, verticillium wilt and rhizoctonia, while cover crops and green manures protect soil and reduce erosion. The crop is economically important both as a staple food and as a high-value processed commodity, and its production risks include late blight, early blight, potato cyst nematodes, aphid-vectored viruses and the Colorado potato beetle, while climate adaptation centres on irrigation, cultivar choice and shifting production windows.",
            "https://edis.ifas.ufl.edu/publication/CV131",
            "UF/IFAS Extension (University of Florida)",
            "2023-08-01", "north_america", "extension",
            ["potato", "seed-tubers", "rotation", "processing", "production", "uf-ifas"],
        ),

        # ---------- RASPBERRY ----------
        "raspberry": Src(
            "Penn State Extension (College of Agricultural Sciences)",
            "Raspberry Production",
            "Raspberry is a temperate bramble fruit grown for fresh market, processing and, increasingly, for tunnel and greenhouse production, and it is one of the most valuable small fruits per unit area. Raspberries are grown as red, black, purple and yellow types, and in two fruiting habits: summer-bearing (floricane) types, which produce on second-year canes, and primocane-bearing (fall-bearing) types, which fruit on first-year canes and allow either one or two crops per season. Production is concentrated in cooler temperate regions with adequate chilling: Penn State Extension describes field production of red and black raspberries and notes that at maturity, about four years old, field plantings of red raspberries should produce roughly 5,000 pounds of fruit per acre, while black raspberry yields are about half those of red raspberries, and that high-tunnel production is at least double that of field production for both red and black raspberries; tunnel-grown primocane-fruiting raspberries may produce a viable harvest the same year they are planted if set out early in the spring. The leading world producers include Russia, Poland, Serbia, the United States, Mexico, Chile and Spain, while in the United States production is concentrated in California, Oregon, Washington and the Northeast, with high-tunnel and primocane systems extending the season. Raspberries require well-drained, fertile soils with good air movement because brambles are susceptible to root rots, and they are grown on raised beds or on flat ground with permanent trellis or a hedgerow row; rotations move bramble blocks periodically to fresh ground to avoid soil-borne disease, and cover crops precede plantings. Raspberry is economically important as a high-value fresh and processed fruit, and its production risks include spotted-wing drosophila, cane blights, phytophthora root rot and viruses, with harvest timing and rapid cooling critical to quality.",
            "https://extension.psu.edu/raspberry-production/",
            "Kathy Demchak, Senior Extension Associate, Penn State Extension (College of Agricultural Sciences)",
            "2021-12-09", "north_america", "extension",
            ["raspberry", "brambles", "primocane", "high-tunnel", "production", "economics"],
        ),

        # ---------- RICE ----------
        "rice": Src(
            "Food and Agriculture Organization of the United Nations (FAO) / University of Arkansas Cooperative Extension Service",
            "Rice — Markets and Trade",
            "Rice is a semi-aquatic cereal and the staple food of more than half the world's population, making it one of the most important crops on Earth both nutritionally and economically. Rice is grown under flooded (lowland) and upland systems and is produced on every continent except Antarctica, but production is heavily concentrated in Asia, which accounts for the large majority of world output and consumption; the leading producers include China, India, Indonesia, Bangladesh, Vietnam, Thailand and Myanmar, with Brazil and the United States the principal producers outside Asia. FAO reports that world rice production continues to expand, reaching record levels in recent seasons on the back of gains in Bangladesh, Brazil, China, India and Indonesia, and that world rice trade is on the order of 60 million tonnes per year, centred on exports from India, Thailand, Vietnam, Pakistan and the United States. The United States produces a comparatively small share of world output but is a major exporter, with production concentrated in Arkansas, Louisiana, Mississippi, Missouri, Texas and California. Rice is grown as an annual crop, established by drilling into a prepared seedbed, broadcasting, or water-seeding onto a flooded field, and the crop is managed around water: a timely flood is established once the crop reaches the correct stage and held at a uniform depth through the season, then drained to permit harvest. Yields vary widely by system and region, commonly ranging from about 3 tonnes per hectare in low-input rainfed systems to 8-10 tonnes per hectare or more in well-managed irrigated systems. Rice fits into rotation with other crops where water and climate allow — in the U.S. South it is commonly rotated with soybean — and rotation helps manage weeds, diseases and soil fertility; flooding itself suppresses many weeds. Rice is economically vital as a staple food, as a source of livelihood for millions of smallholders and as an internationally traded commodity, and its production risks include the rice water weevil, rice stink bug, blast, sheath blight and other diseases, and increasingly water scarcity, salinity and climate-driven drought and flooding.",
            "https://www.fao.org/markets-and-trade/commodities/rice/",
            "Food and Agriculture Organization of the United Nations (FAO)",
            "2023-01-01", "global", "government",
            ["rice", "cereal", "flooded", "staple", "rotation", "fao"],
        ),
    }


# ---------- agriculture records, part 4 (soybean .. zucchini) ----------
def _agriculture_records_4() -> dict[str, Src]:
    return {
        # ---------- SOYBEAN ----------
        "soybean": Src(
            "USDA Economic Research Service (United States Department of Agriculture)",
            "Soybeans and Oil Crops",
            "Soybean is one of the most important oilseed and protein crops in the world and is the second-largest crop by area in the United States, valued as a source of protein meal for livestock feed, vegetable oil for food and industrial use, and biodiesel. Soybeans are adapted to warm, temperate and subtropical climates and are grown as a summer annual; global production is dominated by Brazil, the United States, Argentina, China, India and Paraguay, while in the United States production is concentrated in the Midwest and Corn Belt — Illinois, Iowa, Minnesota, Indiana, Nebraska, Ohio and Missouri — with additional production in the South and eastern states. Soybean is a legume and fixes atmospheric nitrogen when properly inoculated, which makes it the outstanding rotation partner for corn: the corn-soybean rotation is the backbone of U.S. Midwest cropping systems because the soybean crop supplies nitrogen to the following corn crop, breaks pest and disease cycles and improves soil structure. Yields vary widely with region, maturity group and management, with high-yield U.S. Midwest production commonly reaching on the order of 3-4 tonnes per hectare and average global yields lower; soybean is highly responsive to management in narrow rows and with adequate moisture. Soybean ground is commonly planted to cereal rye or other cover crops over winter, which protect the soil from erosion, reduce nutrient loss and suppress weeds. The crop is economically central to U.S. agriculture and to global protein and oil markets, and the United States, Brazil and Argentina dominate world export supply. Climate-adaptation pressures include drought and heat during pod fill, waterlogging, and changes in the length of the growing season, while principal pest and disease pressures include soybean aphid, soybean cyst nematode, sudden death syndrome, soybean rust, white mould and frogeye leaf spot.",
            "https://www.ers.usda.gov/topics/crops/soybeans-and-oil-crops/",
            "USDA Economic Research Service (United States Department of Agriculture)",
            "2023-01-01", "north_america", "government",
            ["soybean", "oilseed", "nitrogen-fixation", "corn-rotation", "export", "usda-ers"],
        ),

        # ---------- SQUASH ----------
        "squash": Src(
            "UF/IFAS Extension (University of Florida, Electronic Data Information Source)",
            "Chapter 7. Cucurbit Production (Vegetable Production Handbook of Florida)",
            "Squash — both summer squash, harvested immature with edible rind, and winter squash, harvested mature with a hard rind — are warm-season cucurbits grown for fresh market and processing and are produced throughout the temperate and subtropical world. Squash require warm conditions and are limited by frost and cool weather, which cause poor fruit set and misshapen fruit, so production is concentrated in warm regions and in seasonal windows that avoid cold: in the United States the major producing states are Florida, Georgia, California, Michigan, New York and the Carolinas for summer squash, with substantial production of winter squash (pumpkins and others) in Illinois, New York, Michigan, Ohio and California, while major world producers include China, India, Ukraine, Russia, the United States and Mexico. In Florida, cucurbits including squash are grown as warm- and cool-season crops on sandy soils, and the Vegetable Production Handbook gives the state's planting dates, recommended cultivars and approved pesticide options. Squash are commonly produced on raised, often fumigated beds with plastic mulch and drip irrigation, which warm the soil, control moisture and reduce fruit rot; the crop can also be grown in high tunnels to extend the season and in the open on bare ground where the season is long. Yields are high in well-managed crops, commonly on the order of 15-40 tonnes per hectare depending on the crop and system. Cucurbits share pests and diseases and should be rotated away from other cucurbits, alternating with cereals, legumes and non-cucurbit vegetables to break disease cycles; cover crops are used before planting to improve soil and organic matter. Squash are economically important both as a fresh-market vegetable and as a processing crop, and their production risks include powdery and downy mildew, squash bug, squash vine borer, cucumber beetles and aphid-transmitted viruses, with adaptation centred on protected culture, resistant cultivars and warm-season timing.",
            "https://edis.ifas.ufl.edu/publication/CV123",
            "UF/IFAS Extension (University of Florida)",
            "2023-08-01", "north_america", "extension",
            ["squash", "cucurbit", "summer-squash", "winter-squash", "rotation", "uf-ifas"],
        ),

        # ---------- STRAWBERRY ----------
        "strawberry": Src(
            "UF/IFAS Extension (University of Florida, Electronic Data Information Source)",
            "Chapter 16. Strawberry Production (Vegetation Production Handbook of Florida)",
            "Strawberry is a high-value small fruit grown for fresh market and processing and is one of the most economically important berry crops in the world, with production concentrated in regions with mild winters and long, warm spring seasons. Production systems differ by region: in California, which dominates U.S. and much of world production, strawberries are grown as an annual hill crop using transplants on raised beds with drip irrigation and plastic mulch, while Florida produces a winter crop under the same intensive system that supplies fresh berries to eastern markets during winter and spring. The leading world producers include China, the United States, Egypt, Mexico, Turkey, Spain and Poland, and in the United States California and Florida account for the large majority of production, with additional acreage in the Pacific Northwest, the Midwest and the Northeast for summer and processing crops. Strawberry is produced as a perennial or short-cycle crop depending on system: annual hill production in California and Florida uses fresh-dug plants set on fumigated, plastic-mulched beds, while matted-row systems, more common in cooler regions, maintain a perennial planting for several seasons. Yields vary enormously with system and region, commonly reaching on the order of 30-70 tonnes per hectare in intensive California and Florida hill culture but far less in matted-row systems. Strawberry is grown on high-organic-matter, well-drained soils and is very dependent on precise water and nutrient management because the plants are shallow-rooted and the fruit is perishable; crop rotation and fumigation are used between cycles to manage soil-borne disease, and cover crops are used to improve soil between strawberry crops. The crop is economically important as a premium fresh-market fruit and as a processed product, and its production risks include botrytis, anthracnose, phytophthora crown rot, two-spotted spider mite, thrips, aphids and spotted-wing drosophila, with adaptation centred on cultivar selection and protected culture.",
            "https://edis.ifas.ufl.edu/publication/CV134",
            "UF/IFAS Extension (University of Florida)",
            "2023-08-01", "north_america", "extension",
            ["strawberry", "annual-hill", "plastic-mulch", "production", "botrytis", "uf-ifas"],
        ),

        # ---------- TOBACCO ----------
        "tobacco": Src(
            "USDA Economic Research Service (United States Department of Agriculture) / Penn State Extension",
            "Tobacco Production and Farm Economics",
            "Tobacco is a warm-season specialty field crop grown for its leaves and is one of the most economically valuable crops per unit area in the regions where it is produced, though its cultivation and trade are shaped by health policy and global demand trends. Tobacco is grown in temperate and subtropical regions and is divided into types by curing method and use — flue-cured, burley, dark air-cured, fire-cured and cigar types — each with distinctive production and marketing requirements. The major world producers include China, which dominates world output, followed by India, Brazil, the United States, Indonesia, Turkey and Zimbabwe, while in the United States production is concentrated in North Carolina, Kentucky, Virginia, Tennessee, South Carolina, Pennsylvania and Georgia. Penn State Extension describes tobacco production in Pennsylvania, where about 7,000 acres produce the local Lancaster County type 41 variety used for cigar wrappers, and notes that tobacco has been grown there since colonial times. Tobacco is grown from transplants rather than direct-seeded and is traditionally cultivated numerous times through the season to eliminate weeds and competition and loosen the soil; Penn State Extension describes how this cultivation leaves the soil loose and prone to erosion and nutrient loss on sloping ground, and therefore promotes no-till transplanting into a cover crop such as clover, rye or wheat, which protects the soil with a residue mat, increases soil health and reduces runoff, erosion and nutrient pollution while producing uniform, high-quality crops. Because tobacco is a high-value crop it is often grown on smaller acreages and is economically important to farm income in producing regions and to the economies of some states and countries, and it is also a significant world export commodity. Production risks include black shank, granville wilt, tobacco mosaic virus, hornworms, aphids and flea beetles, and adaptation in producing regions centres on rotation, resistant varieties and integrated pest and soil management.",
            "https://extension.psu.edu/no-till-innovations-in-tobacco-video/",
            "Jeffrey Graybill, Penn State Extension (College of Agricultural Sciences)",
            "2022-01-01", "north_america", "extension",
            ["tobacco", "specialty-crop", "transplanting", "no-till", "economics", "production"],
        ),

        # ---------- TOMATO ----------
        "tomato": Src(
            "UF/IFAS Extension (University of Florida, Electronic Data Information Source)",
            "Chapter 18. Tomato Production (Vegetable Production Handbook of Florida)",
            "Tomato is the most widely grown and most economically important fruiting vegetable in the world, consumed fresh and processed into sauces, paste, juice and canned products. Tomatoes are adapted to warm conditions and are grown across temperate, subtropical and tropical regions in the open, under plasticulture and in protected culture; global production is dominated by China, India, the United States, Turkey, Egypt, Italy, Spain and Mexico, while in the United States commercial production is concentrated in California, which leads processing tomato production worldwide, and in Florida, Georgia and other states for fresh-market winter and spring supply. UF/IFAS's Vegetable Production Handbook describes tomato production in Florida as a major fresh-market industry with more than 40,000 acres harvested in the state at a gross sales value in excess of $580 million, grown throughout the state in five main regions — southeast around Homestead, east central at Fort Pierce, southwest at Immokalee, west central at Tampa and northwest at Quincy — which illustrates both the scale and the geographic concentration of fresh-market production. Tomato is grown from transplants, mostly on raised, fumigated beds with plastic mulch and drip irrigation, and the crop is a heavy feeder that requires closely managed water and nutrients; the handbook notes that tissue analysis is used on some soils in place of calibrated soil tests and that fertigation with a 4-0-8 or similar formula is initiated a few weeks after transplanting, with rates increased as plant biomass grows. Yields are high, commonly on the order of 40-80 tonnes per hectare in well-managed fields of California and Florida. Tomato rotates well with cereals, legumes and brassicas and away from solanaceous crops to reduce soil-borne disease; cover crops improve soil and, where residue is incorporated, reduce fertilizer requirements. The crop is economically important both fresh and processed, and its production risks include the silverleaf whitefly and the tomato yellow leaf curl virus it vectors, late blight, bacterial spot, fusarium wilt, tomato fruitworm and leafminer, with adaptation centred on resistant cultivars and protected culture.",
            "https://edis.ifas.ufl.edu/publication/CV137",
            "UF/IFAS Extension (University of Florida)",
            "2023-08-01", "north_america", "extension",
            ["tomato", "fresh-market", "plasticulture", "rotation", "production", "uf-ifas"],
        ),

        # ---------- ZUCCHINI ----------
        "zucchini": Src(
            "UF/IFAS Extension (University of Florida, Electronic Data Information Source)",
            "Chapter 7. Cucurbit Production (Vegetable Production Handbook of Florida)",
            "Zucchini is a summer squash and a warm-season cucurbit harvested immature, grown for fresh market and increasingly for value-added and processed products, and it is produced throughout temperate and subtropical regions where a warm growing season is available. Zucchini is the most widely grown summer squash and is produced both in the open and under high tunnels and protected culture, which extend the season and improve fruit quality; production is limited by frost and cool weather, which cause poor fruit set and misshapen fruit, so it is concentrated in warm climates and in seasonal windows that avoid cold. In the United States the major producing states include Florida, Georgia, California, Michigan, New York and the Carolinas, while major world producers include China, India, Ukraine, Turkey, Italy, Spain and Mexico. In Florida, cucurbits including zucchini are grown as warm- and cool-season crops on the state's sandy soils, and the Vegetable Production Handbook gives the state's planting dates, recommended cultivars and approved pesticide options. Zucchini is commonly produced on raised, often fumigated beds with plastic mulch and drip irrigation, which warm the soil, retain moisture and reduce fruit rot, and the crop is harvested repeatedly through a long picking window, which makes timely picking essential to keep plants productive and fruit tender. Yields are high in well-managed crops, commonly on the order of 15-40 tonnes per hectare over the season. Cucurbits share pests and diseases and should be rotated away from other cucurbits, alternating with cereals, legumes and non-cucurbit vegetables to break disease cycles, and cover crops are used before planting to improve soil and organic matter. Zucchini is economically important as a fast-turnover fresh-market vegetable with a long harvest window, and its production risks include powdery and downy mildew, squash bug, squash vine borer, cucumber beetles and aphid-transmitted viruses, with adaptation centred on protected culture, resistant cultivars and warm-season timing.",
            "https://edis.ifas.ufl.edu/publication/CV123",
            "UF/IFAS Extension (University of Florida)",
            "2023-08-01", "north_america", "extension",
            ["zucchini", "summer-squash", "cucurbit", "plastic-mulch", "rotation", "uf-ifas"],
        ),
    }
