create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  plan text not null default 'free',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.diagnoses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  source_filename text,
  status text not null default 'completed' check (status in ('processing', 'completed', 'failed')),
  model_info jsonb not null default '{}'::jsonb,
  inference_ms numeric,
  low_confidence boolean not null default false,
  low_confidence_threshold numeric,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  diagnosis_id uuid not null references public.diagnoses(id) on delete cascade,
  class_id integer not null,
  label text not null,
  confidence numeric not null check (confidence >= 0 and confidence <= 1),
  rank integer not null check (rank > 0),
  created_at timestamptz not null default now(),
  unique (diagnosis_id, rank)
);

create table if not exists public.uploaded_images (
  id uuid primary key default gen_random_uuid(),
  diagnosis_id uuid references public.diagnoses(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  bucket text not null default 'diagnosis-images',
  storage_path text not null,
  original_filename text,
  content_type text,
  byte_size bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  diagnosis_id uuid references public.diagnoses(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  bucket text not null default 'diagnosis-reports',
  storage_path text,
  report_type text not null default 'json',
  created_at timestamptz not null default now()
);

create table if not exists public.agent_executions (
  id uuid primary key default gen_random_uuid(),
  diagnosis_id uuid references public.diagnoses(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  agent_name text not null,
  status text not null check (status in ('queued', 'running', 'completed', 'failed')),
  input jsonb not null default '{}'::jsonb,
  output jsonb not null default '{}'::jsonb,
  error text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name) values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.diagnoses enable row level security;
alter table public.predictions enable row level security;
alter table public.uploaded_images enable row level security;
alter table public.reports enable row level security;
alter table public.agent_executions enable row level security;

create policy "users manage own profile" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "users read own diagnoses" on public.diagnoses for select using (auth.uid() = user_id);
create policy "users create own diagnoses" on public.diagnoses for insert with check (auth.uid() = user_id);
create policy "users read own predictions" on public.predictions for select using (exists (select 1 from public.diagnoses d where d.id = diagnosis_id and d.user_id = auth.uid()));
create policy "users create own predictions" on public.predictions for insert with check (exists (select 1 from public.diagnoses d where d.id = diagnosis_id and d.user_id = auth.uid()));
create policy "users manage own images" on public.uploaded_images for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own reports" on public.reports for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own agent executions" on public.agent_executions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public) values ('diagnosis-images', 'diagnosis-images', false) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('diagnosis-reports', 'diagnosis-reports', false) on conflict (id) do nothing;

create policy "users manage own diagnosis images" on storage.objects for all
using (bucket_id = 'diagnosis-images' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'diagnosis-images' and (storage.foldername(name))[1] = auth.uid()::text);

create policy "users manage own diagnosis reports" on storage.objects for all
using (bucket_id = 'diagnosis-reports' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'diagnosis-reports' and (storage.foldername(name))[1] = auth.uid()::text);
